// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { apiRequest } from '../../src/client/api/client';
import { LoginPage, RegisterPage } from '../../src/client/auth/AuthPages';
import { ProtectedRoute } from '../../src/client/auth/ProtectedRoute';
const user={id:'u1',email:'person@example.com',displayName:'A Person',baseCurrency:'EUR',timezone:'Europe/Sofia',emailVerifiedAt:null,createdAt:'2025-01-01'};
const json=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));
const wrap=(node:React.ReactNode,initial='/login')=>{const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[initial]}><Routes><Route path="/login" element={node}/><Route path="/register" element={node}/><Route path="/" element={<div>Dashboard ready</div>}/></Routes></MemoryRouter></QueryClientProvider>)};
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe('session authentication UI',()=>{
  it('submits login once and restores the authenticated route',async()=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(()=>json({data:{user}}));wrap(<LoginPage/>);await userEvent.type(screen.getByLabelText('Email'),'person@example.com');await userEvent.type(screen.getByLabelText('Password'),'Correct-Horse-47!');await userEvent.click(screen.getByRole('button',{name:/sign in/i}));await screen.findByText('Dashboard ready');expect(fetchMock).toHaveBeenCalledTimes(1);expect(fetchMock.mock.calls[0]?.[1]).toMatchObject({method:'POST',credentials:'include'});expect(String(fetchMock.mock.calls[0]?.[1]?.body)).not.toContain('token')});
  it('submits registration with display name and secure cookie credentials',async()=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(()=>json({data:{user}},201));wrap(<RegisterPage/>,'/register');await userEvent.type(screen.getByLabelText('Name'),'A Person');await userEvent.type(screen.getByLabelText('Email'),'person@example.com');await userEvent.type(screen.getByLabelText(/^Password/),'Correct-Horse-47!');await userEvent.click(screen.getByRole('button',{name:/create account/i}));await screen.findByText('Dashboard ready');expect(String(fetchMock.mock.calls[0]?.[1]?.body)).toContain('displayName')});
  it('redirects an unauthenticated protected route to login',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>json({error:{code:'unauthenticated',message:'Sign in.'}},401));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/private']}><Routes><Route path="/private" element={<ProtectedRoute><div>Secret</div></ProtectedRoute>}/><Route path="/login" element={<div>Login destination</div>}/></Routes></MemoryRouter></QueryClientProvider>);expect(await screen.findByText('Login destination')).toBeInTheDocument();expect(screen.queryByText('Secret')).not.toBeInTheDocument()});
  it('broadcasts session expiration on ordinary API 401',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(()=>json({error:{code:'unauthenticated',message:'Expired'}},401));const listener=vi.fn();window.addEventListener('spendime:unauthorized',listener);await expect(apiRequest('/api/accounts')).rejects.toMatchObject({status:401});expect(listener).toHaveBeenCalledOnce();window.removeEventListener('spendime:unauthorized',listener)});
  it('prevents duplicate submissions while login is pending',async()=>{let resolve!: (value:Response)=>void;vi.spyOn(globalThis,'fetch').mockImplementation(()=>new Promise(r=>{resolve=r}));wrap(<LoginPage/>);fireEvent.change(screen.getByLabelText('Email'),{target:{value:'person@example.com'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'Correct-Horse-47!'}});const button=screen.getByRole('button',{name:/sign in/i});fireEvent.click(button);expect(await screen.findByRole('button',{name:/please wait/i})).toBeDisabled();resolve(new Response(JSON.stringify({data:{user}}),{status:200,headers:{'Content-Type':'application/json'}}));await waitFor(()=>expect(screen.getByText('Dashboard ready')).toBeInTheDocument())});
});
