import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRightLeft, Landmark, RefreshCw, Unplug } from 'lucide-react';
import { useState } from 'react';
import { apiRequest, jsonBody } from '../api/client';
import { keys, useAccounts, useCategories } from '../api/queries';
import type { Account, ApiEnvelope } from '../api/types';
import { Badge, Button, Card, EmptyState, ErrorState, Field, FormError, Input, LoadingState, PageHeader, Select } from '../components/ui';
import { formatMoney } from '../utils/money';

type Institution = { name:string; country:string; beta:boolean };
type Link = { id:string; name:string; currency:string; accountId:string|null; reportedBalance:string|null; balanceAsOf:string|null; balanceStatus:string; lastSyncedAt:string|null; ledgerBalance:string|null };
type Connection = { id:string; provider:string; environment:string; institutionName:string; institutionCountry:string; status:string; consentExpiresAt:string|null; lastSyncedAt:string|null; nextSyncAt:string|null; errorCode:string|null; accounts:Link[] };
type Review = { id:string; accountName:string; direction:string; amount:string; currency:string; occurredOn:string; merchant:string|null; description:string|null; status:string; ledgerTransactionId:string|null; proposedAmount:string|null; proposedCurrency:string|null; proposedOccurredOn:string|null };
type Candidate = { id:string; description:string|null; merchant:string|null; amount:string; currency:string; occurredAt:string; kind:string };
type PairCandidate = { id:string; direction:string; amount:string; currency:string; occurredOn:string; merchant:string|null; accountName:string };
type Rule = { id:string; merchantKey:string; direction:'debit'|'credit'; categoryId:string; categoryName:string };
const get = async <T,>(path:string) => (await apiRequest<ApiEnvelope<T>>(path)).data;
const post = async <T,>(path:string, body?:unknown) => (await apiRequest<ApiEnvelope<T>>(path,{method:'POST',...(body===undefined?{}:jsonBody(body))})).data;
const date = (value:string|null) => value ? new Date(value).toLocaleString() : 'Not yet';

export default function BankingPage() {
  const qc=useQueryClient();
  const [country,setCountry]=useState('BG'); const [search,setSearch]=useState('');
  const [notice,setNotice]=useState(new URLSearchParams(location.search).get('result'));
  const [debit,setDebit]=useState(''); const [credit,setCredit]=useState('');
  const [ruleMerchant,setRuleMerchant]=useState(''); const [ruleDirection,setRuleDirection]=useState<'debit'|'credit'>('debit'); const [ruleCategory,setRuleCategory]=useState('');
  const institutions=useQuery({queryKey:['banking','institutions',country],queryFn:()=>get<Institution[]>(`/api/banking/institutions?country=${country}`),retry:false});
  const connections=useQuery({queryKey:['banking','connections'],queryFn:()=>get<Connection[]>('/api/banking/connections'),refetchInterval:30_000,retry:false});
  const reviews=useQuery({queryKey:['banking','review'],queryFn:()=>get<Review[]>('/api/banking/review'),retry:false});
  const transfers=useQuery({queryKey:['banking','transfers'],queryFn:()=>get<PairCandidate[]>('/api/banking/transfers/candidates'),retry:false});
  const ai=useQuery({queryKey:['banking','ai'],queryFn:()=>get<{available:boolean;enabled:boolean}>('/api/banking/ai'),retry:false});
  const rules=useQuery({queryKey:['banking','rules'],queryFn:()=>get<Rule[]>('/api/banking/rules'),retry:false});
  const accounts=useAccounts(false);
  const categories=useCategories(false);
  const refresh=async()=>{await Promise.all([qc.invalidateQueries({queryKey:['banking']}),qc.invalidateQueries({queryKey:keys.accounts}),qc.invalidateQueries({queryKey:keys.transactions}),qc.invalidateQueries({queryKey:keys.dashboard})]);};
  const connect=useMutation({mutationFn:(bank:Institution)=>post<{authorizationUrl:string}>('/api/banking/connections',{country:bank.country,name:bank.name}),onSuccess:(value)=>{location.assign(value.authorizationUrl);}});
  const renew=useMutation({mutationFn:(id:string)=>post<{authorizationUrl:string}>(`/api/banking/connections/${id}/renew`),onSuccess:(value)=>{location.assign(value.authorizationUrl);}});
  const sync=useMutation({mutationFn:(id:string)=>post(`/api/banking/connections/${id}/sync`),onSuccess:refresh});
  const disconnect=useMutation({mutationFn:(id:string)=>apiRequest(`/api/banking/connections/${id}/disconnect`,{method:'POST'}),onSuccess:refresh});
  const forget=useMutation({mutationFn:(id:string)=>apiRequest(`/api/banking/connections/${id}/data`,{method:'DELETE'}),onSuccess:refresh});
  const link=useMutation({mutationFn:({id,accountId}:{id:string;accountId:string|null})=>post(`/api/banking/links/${id}/link`,{accountId}),onSuccess:refresh});
  const reconcile=useMutation({mutationFn:(id:string)=>post(`/api/banking/links/${id}/reconcile`),onSuccess:refresh});
  const pair=useMutation({mutationFn:()=>post('/api/banking/transfers/pair',{debitId:debit,creditId:credit}),onSuccess:async()=>{setDebit('');setCredit('');await refresh();}});
  const setAi=useMutation({mutationFn:async(enabled:boolean)=>(await apiRequest<ApiEnvelope<{enabled:boolean}>>('/api/banking/ai',{method:'PUT',...jsonBody({enabled})})).data,onSuccess:refresh});
  const saveRule=useMutation({mutationFn:()=>post('/api/banking/rules',{merchant:ruleMerchant,direction:ruleDirection,categoryId:ruleCategory}),onSuccess:async()=>{setRuleMerchant('');setRuleCategory('');await refresh();}});
  const deleteRule=useMutation({mutationFn:(id:string)=>apiRequest(`/api/banking/rules/${id}`,{method:'DELETE'}),onSuccess:refresh});
  const bankList=institutions.data?.filter((item)=>item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())) ?? [];
  return <>
    <PageHeader eyebrow="Open banking" title="Banking" description="Connect a bank through its secure authorization page. This integration currently uses Enable Banking's evaluation environment." />
    <Card className="mb-5 border-amber-200 bg-amber-50/70"><div className="flex flex-wrap items-center gap-2"><Badge tone="warning">Sandbox / evaluation</Badge><p className="text-sm text-muted">Availability and bank behavior depend on Enable Banking. Public production access requires separate approval.</p></div></Card>
    {notice && <Card className="mb-5"><p className="text-sm">{notice==='connected'?'Bank authorization completed. Link each account below to import it.':'Bank authorization was not completed. You can try again.'}</p><Button variant="ghost" onClick={()=>{setNotice(null);history.replaceState({},'',location.pathname);}}>Dismiss</Button></Card>}
    <Card className="mb-5"><div className="mb-4 flex items-center gap-2"><Landmark className="size-5 text-brand"/><h2 className="font-bold">Connect a bank</h2></div>
      <div className="grid gap-3 sm:grid-cols-[140px_1fr]"><Field label="Country"><Select value={country} onChange={(e)=>setCountry(e.target.value)}><option value="BG">Bulgaria</option><option value="DE">Germany</option><option value="FR">France</option><option value="NL">Netherlands</option></Select></Field><Field label="Search banks"><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search by bank name" /></Field></div>
      {institutions.isPending?<LoadingState label="Loading available banks…"/>:institutions.isError?<ErrorState error={institutions.error} retry={()=>institutions.refetch()}/>:<div className="mt-4 grid max-h-64 gap-2 overflow-auto">{bankList.length?bankList.map((bank)=><div key={`${bank.country}:${bank.name}`} className="flex items-center justify-between gap-2 rounded-2xl border border-brand/10 px-3 py-2"><span className="min-w-0 truncate text-sm font-medium">{bank.name} {bank.beta&&<Badge tone="warning">Beta</Badge>}</span><Button variant="secondary" disabled={connect.isPending} onClick={()=>connect.mutate(bank)}>Connect</Button></div>):<p className="py-4 text-sm text-muted">No matching banks were returned for this country.</p>}</div>}
      <FormError error={connect.error}/><p className="mt-3 text-xs text-muted">Spendime never asks for your banking password. Authorization happens with your bank through Enable Banking.</p>
    </Card>
    <div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Connected banks</h2><Button variant="ghost" onClick={()=>refresh()}><RefreshCw className="size-4"/>Refresh</Button></div>
    {connections.isPending?<LoadingState/>:connections.isError?<ErrorState error={connections.error} retry={()=>connections.refetch()}/>:!connections.data?.length?<EmptyState icon={<Landmark/>} title="No banks connected" description="Select a bank above to start a secure authorization."/>:<div className="grid gap-4">{connections.data.map((connection)=><Card key={connection.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{connection.institutionName}</h3><p className="text-xs text-muted">Last sync: {date(connection.lastSyncedAt)} · Consent ends: {date(connection.consentExpiresAt)}</p></div><Badge tone={connection.status==='active'?'positive':'warning'}>{connection.status}</Badge></div>
      {connection.errorCode&&<p className="mt-2 text-sm text-amber-800">{connection.errorCode==='consent_expired'?'Authorization expired. Renew to resume syncing.':connection.errorCode==='rate_limited'?'Bank requests are temporarily limited. Sync will retry later.':connection.errorCode==='authorization_failed'?'Authorization failed. Renew and try again.':connection.errorCode==='remote_revocation_unconfirmed'?'Local access was removed, but the bank did not confirm remote revocation. Revoke Spendime in your bank settings if needed.':'The last sync failed. Try again later.'}</p>}
      <div className="mt-4 grid gap-3">{connection.accounts.map((item)=><BankLink key={item.id} item={item} accounts={accounts.data??[]} link={link} reconcile={reconcile} canLink={connection.status==='active'}/>)}</div>
      <div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" disabled={sync.isPending||connection.status!=='active'||Boolean(connection.nextSyncAt&&new Date(connection.nextSyncAt)>new Date())} onClick={()=>sync.mutate(connection.id)}><RefreshCw className="size-4"/>Sync now</Button><Button variant="secondary" disabled={renew.isPending||connection.status==='disconnected'} onClick={()=>renew.mutate(connection.id)}>Renew access</Button><Button variant="danger" disabled={disconnect.isPending||connection.status==='disconnected'} onClick={()=>{if(confirm(`Disconnect ${connection.institutionName}? Imported transactions remain in your ledger.`))disconnect.mutate(connection.id);}}><Unplug className="size-4"/>Disconnect</Button>{connection.status==='disconnected'&&<Button variant="danger" disabled={forget.isPending} onClick={()=>{if(confirm('Remove stored bank connection and staging data? Imported ledger entries remain.'))forget.mutate(connection.id);}}>Remove bank data</Button>}</div><FormError error={sync.error||renew.error||disconnect.error||forget.error}/>
    </Card>)}</div>}
    <Card className="mt-5"><h2 className="font-bold">Review imported transactions</h2><p className="mt-1 text-sm text-muted">Transactions linked to an existing money account wait here to prevent double counting. Match an existing entry or post a new one.</p>{reviews.data?.length?reviews.data.map((item)=><ReviewRow key={item.id} item={item} refresh={refresh}/>):<p className="mt-3 text-sm text-muted">Nothing needs review.</p>}</Card>
    <Card className="mt-5"><h2 className="flex items-center gap-2 font-bold"><ArrowRightLeft className="size-5"/>Pair your own transfers</h2><p className="mt-1 text-sm text-muted">Pair a debit and credit between your connected accounts, including transfers with different currencies. This removes them from spending and income.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Money sent"><Select value={debit} onChange={(e)=>setDebit(e.target.value)}><option value="">Choose debit</option>{transfers.data?.filter(x=>x.direction==='debit').map(x=><option key={x.id} value={x.id}>{x.occurredOn} · {x.accountName} · {formatMoney(x.amount,x.currency)}</option>)}</Select></Field><Field label="Money received"><Select value={credit} onChange={(e)=>setCredit(e.target.value)}><option value="">Choose credit</option>{transfers.data?.filter(x=>x.direction==='credit').map(x=><option key={x.id} value={x.id}>{x.occurredOn} · {x.accountName} · {formatMoney(x.amount,x.currency)}</option>)}</Select></Field></div><Button className="mt-3" disabled={!debit||!credit||pair.isPending} onClick={()=>pair.mutate()}>Pair transfer</Button><FormError error={pair.error}/></Card>
    <Card className="mt-5"><h2 className="font-bold">Merchant rules</h2><p className="mt-1 text-sm text-muted">Your rules categorize future bank transactions from the same merchant before automatic suggestions.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Merchant"><Input value={ruleMerchant} onChange={(e)=>setRuleMerchant(e.target.value)} placeholder="Merchant name"/></Field><Field label="Direction"><Select value={ruleDirection} onChange={(e)=>{setRuleDirection(e.target.value as 'debit'|'credit');setRuleCategory('');}}><option value="debit">Money sent</option><option value="credit">Money received</option></Select></Field><Field label="Category"><Select value={ruleCategory} onChange={(e)=>setRuleCategory(e.target.value)}><option value="">Choose category</option>{categories.data?.filter(c=>c.kind==='both'||c.kind===(ruleDirection==='debit'?'expense':'income')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field></div><Button className="mt-3" disabled={!ruleMerchant.trim()||!ruleCategory||saveRule.isPending} onClick={()=>saveRule.mutate()}>Save rule</Button><div className="mt-3 grid gap-2">{rules.data?.map(rule=><div key={rule.id} className="flex items-center justify-between gap-2 rounded-xl bg-brand/[.04] px-3 py-2 text-sm"><span>{rule.merchantKey} · {rule.direction==='debit'?'Sent':'Received'} → {rule.categoryName}</span><Button variant="ghost" disabled={deleteRule.isPending} onClick={()=>deleteRule.mutate(rule.id)}>Remove</Button></div>)}</div><FormError error={saveRule.error||deleteRule.error}/></Card>
    <Card className="mt-5"><h2 className="font-bold">Optional AI categorization</h2><p className="mt-1 text-sm text-muted">Deterministic rules work without external AI. Gemini remains off unless a paid project and privacy requirements are configured, and you opt in. Short transaction text and existing category names may then be sent to Google.</p><Button className="mt-3" variant="secondary" disabled={!ai.data?.available||setAi.isPending} onClick={()=>setAi.mutate(!ai.data?.enabled)}>{ai.data?.enabled?'Disable Gemini':'Enable Gemini'}</Button>{!ai.data?.available&&<p className="mt-2 text-xs text-muted">Unavailable on this installation.</p>}<FormError error={setAi.error}/></Card>
  </>;
}

function BankLink({item,accounts,link,reconcile,canLink}:{item:Link;accounts:Account[];link:any;reconcile:any;canLink:boolean}) {
  const [selected,setSelected]=useState('');
  return <div className="rounded-2xl border border-brand/10 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{item.name} · {item.currency}</p><p className="text-xs text-muted">Last sync: {date(item.lastSyncedAt)}</p></div><Badge tone={item.accountId?'positive':'warning'}>{item.accountId?'Linked':'Needs linking'}</Badge></div>
    {item.reportedBalance!==null&&<p className="mt-2 text-sm">Bank reported: <strong>{formatMoney(item.reportedBalance,item.currency)}</strong>{item.ledgerBalance!==null&&<> · Spendime ledger: <strong>{formatMoney(item.ledgerBalance,item.currency)}</strong></>}</p>}
    {!item.accountId&&canLink?<div className="mt-3 flex flex-wrap gap-2"><Button disabled={link.isPending} onClick={()=>link.mutate({id:item.id,accountId:null})}>Create money account</Button><Select aria-label="Link to existing money account" value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Choose existing account</option>{accounts.filter((a)=>a.currency===item.currency&&!a.isArchived).map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</Select><Button variant="secondary" disabled={!selected||link.isPending} onClick={()=>link.mutate({id:item.id,accountId:selected})}>Link existing</Button><p className="w-full text-xs text-muted">Existing accounts require review before imported transactions enter the ledger.</p></div>:item.balanceStatus!=='reconciled'&&item.reportedBalance!==null&&item.lastSyncedAt&&<div className="mt-3"><Button variant="secondary" disabled={reconcile.isPending} onClick={()=>{if(confirm('Calibrate this new account opening balance to the bank reported balance?'))reconcile.mutate(item.id);}}>Calibrate new account balance</Button></div>}
    <FormError error={link.error||reconcile.error}/>
  </div>;
}

function ReviewRow({item,refresh}:{item:Review;refresh:()=>Promise<void>}) {
  const [selected,setSelected]=useState('');
  const candidates=useQuery({queryKey:['banking','candidates',item.id],queryFn:()=>get<Candidate[]>(`/api/banking/review/${item.id}/candidates`)});
  const postTx=useMutation({mutationFn:()=>post(`/api/banking/review/${item.id}/post`),onSuccess:refresh});
  const match=useMutation({mutationFn:()=>post(`/api/banking/review/${item.id}/match`,{transactionId:selected}),onSuccess:refresh});
  const keep=useMutation({mutationFn:()=>post(`/api/banking/review/${item.id}/keep`),onSuccess:refresh});
  return <div className="mt-3 rounded-2xl border border-brand/10 p-3"><p className="text-sm font-semibold">{item.occurredOn} · {item.accountName} · {item.merchant||item.description||'Bank transaction'}</p><p className="text-sm text-muted">{item.direction==='credit'?'+':'−'}{formatMoney(item.amount,item.currency)}</p>{item.ledgerTransactionId?<div className="mt-2"><p className="mb-2 text-sm text-amber-800">This bank record changed after import. Your existing ledger entry was preserved. {(item.proposedAmount||item.proposedCurrency)&&`Bank now reports ${formatMoney(item.proposedAmount||item.amount,item.proposedCurrency||item.currency)}.`} {item.proposedOccurredOn&&`New date: ${item.proposedOccurredOn}.`}</p><Button variant="secondary" disabled={keep.isPending} onClick={()=>keep.mutate()}>Keep existing entry</Button></div>:<div className="mt-2 flex flex-wrap gap-2"><Select aria-label="Matching existing transaction" value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Choose an existing entry</option>{candidates.data?.map(x=><option key={x.id} value={x.id}>{new Date(x.occurredAt).toLocaleDateString()} · {x.description||x.merchant||x.kind} · {formatMoney(x.amount,x.currency)}</option>)}</Select><Button variant="secondary" disabled={!selected||match.isPending} onClick={()=>match.mutate()}>Match entry</Button><Button disabled={postTx.isPending} onClick={()=>postTx.mutate()}>Post as new</Button></div>}<FormError error={postTx.error||match.error||keep.error}/></div>;
}
